name: CI

on:
  pull_request:
    branches:
      - main  

jobs:
  pytests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry 
          poetry install  

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)  # Set the PYTHONPATH
          poetry run pytest tests

